Custom Field Constrains 1.2.3:
Support team workflow - use parent entity states
 - Since mashup is configured for parent workflow entity state, we should use parent workflow entity state for team workflow state when apply mashup constraints.
 - Query entity states by workflow process, since custom workflow entity states have no Process field set & Process field is deprecated. See https://plan.tpondemand.com/api/v1/EntityStates/meta for details.
- Support for team workflow in quick add - custom handling of team entity states.
- Performance fixes - bulk Entity State queries + Custom Fields cache.
- Fixed a couple of bugs with support of custom fields with same names in different processes.
- Tests for checks of parent EntityStates constraints application.

Fix `TypeError: e.toLowerCase is not a function`